/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Estacionamento;

import javax.swing.JOptionPane;

/**
 *
 * @author socor
 */
public class Cadastro extends javax.swing.JFrame {

    /**
     * Creates new form Cadastro
     */
    public Cadastro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jTextFieldPlacaveiculo = new javax.swing.JTextField();
        jTextFieldModeloveiculo = new javax.swing.JTextField();
        jTextFieldCPF = new javax.swing.JTextField();
        jTextFieldNome = new javax.swing.JTextField();
        jButtonCadastrar = new javax.swing.JButton();
        jLabelPlacaveiculo = new javax.swing.JLabel();
        jLabelModeloVeiculo = new javax.swing.JLabel();
        jLabelTelefone = new javax.swing.JLabel();
        jLabelNome = new javax.swing.JLabel();
        jLabelPainel = new javax.swing.JLabel();

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Design sem nome (6) (1) (2).png"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jTextFieldPlacaveiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 420, 390, 30));
        getContentPane().add(jTextFieldModeloveiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 380, 390, 30));
        getContentPane().add(jTextFieldCPF, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 340, 390, 30));
        getContentPane().add(jTextFieldNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 300, 390, 30));

        jButtonCadastrar.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jButtonCadastrar.setText("CADASTRAR");
        jButtonCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastrarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 490, -1, -1));

        jLabelPlacaveiculo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabelPlacaveiculo.setText("PLACA DO VEÍCULO:");
        getContentPane().add(jLabelPlacaveiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 420, -1, -1));

        jLabelModeloVeiculo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabelModeloVeiculo.setText("MODELO DO VEÍCULO:");
        getContentPane().add(jLabelModeloVeiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 380, -1, -1));

        jLabelTelefone.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabelTelefone.setText("TELEFONE:");
        getContentPane().add(jLabelTelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 340, -1, -1));

        jLabelNome.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabelNome.setText("NOME:");
        getContentPane().add(jLabelNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 300, -1, -1));

        jLabelPainel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/layout parking.jpeg"))); // NOI18N
        getContentPane().add(jLabelPainel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, -1, 660));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastrarActionPerformed
       
            JOptionPane.showMessageDialog(null, "Cliente cadastrado com sucesso ");
    }//GEN-LAST:event_jButtonCadastrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCadastrar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelModeloVeiculo;
    private javax.swing.JLabel jLabelNome;
    private javax.swing.JLabel jLabelPainel;
    private javax.swing.JLabel jLabelPlacaveiculo;
    private javax.swing.JLabel jLabelTelefone;
    private javax.swing.JTextField jTextFieldCPF;
    private javax.swing.JTextField jTextFieldModeloveiculo;
    private javax.swing.JTextField jTextFieldNome;
    private javax.swing.JTextField jTextFieldPlacaveiculo;
    // End of variables declaration//GEN-END:variables
}
